name: "Build"

on:
  workflow_call:
    inputs:
      arch:
        description: 'Build architecture (x64 or arm64)'
        required: true
        type: string
      build_type:
        description: 'Build type (Debug or Release)'
        required: true
        type: string
      codeql:
        description: 'Perform CodeQL analysis'
        required: false
        type: boolean
        default: false

jobs:
  build_setup:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      if: ${{ inputs.codeql }}
      uses: github/codeql-action/init@v1
      with:
        languages: cpp

    - name: Install Windows SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
      with:
        sdk-version: 19041

    - name: Build
      run: |
        mkdir build && pushd build
        cmake -A ${{ inputs.arch }} -DBYPASS_WLANAPI_DEPENDENCY=ON -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} ..
        cmake --build . --parallel --config ${{ inputs.build_type }}
        popd

    - name: Perform CodeQL Analysis
      if: ${{ inputs.codeql }}
      uses: github/codeql-action/analyze@v1

    - name: Collect test artifact
      uses: actions/upload-artifact@v2
      with:
        name: proxy-wifi-test-${{ inputs.arch }}-${{ inputs.build_type }}
        path: build/test/${{ inputs.build_type }}/proxy-wifi-test.exe